In [1]:
import numpy as np

The Basics

In [2]:
a = np.array([1,2,3],dtype='int16') #'int 16 or 32 or 64 and so on'
# a = np.array([1,2,3],dtype='int')
# a = np.array([1,2,3],dtype='i16')
# a = np.array([1,2,3],dtype='i')

In [3]:
b=np.array([[1,2,3],[4,5,6]],dtype='int32') # 2d
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
# Get Dimension
#a.ndim
b.ndim

2

In [5]:
# Get Shape of arr or matrix --> row * cols 
b.shape

(2, 3)

In [6]:
# get Item size
b.itemsize   # how many of bytes 4 byte --> 32 bits

4

In [7]:
# the total size
b.nbytes 

24

In [8]:
# Get Type
b.dtype

dtype('int32')

In [9]:
b.size # --> number of elements (length)

6

In [10]:
# change data type
arr =np.array([1,0,0,-5,5])
newArr=arr.astype('bool')
print(newArr)

[ True False False  True  True]


Accessing/Changing specific elements, rows, columns, etc

In [11]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
print(a[0][2])

3


In [13]:
# Print all the array
print(a[:,:])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
# Get a row --> put value on row
print(a[0,:])

[1 2 3 4 5 6 7]


In [15]:
# Get a column --> put value on column
print(a[:,0])

[1 8]


In [16]:
a[0,:] # first row
a[:,0] # first col

array([1, 8])

In [17]:
# 1st element
a[0,0]
# last element
a[-1,-1]

14

In [18]:
#  [startindex:endindex:stepsize]
print(a[0, 0:-1:2]) # [1 '2' 3 '4' 5 '6' 7]

[1 3 5]


In [40]:
aZeros=np.zeros((2,2))
print(aZeros)

[[0. 0.]
 [0. 0.]]


In [20]:
ones=np.ones((3,3),dtype='int32')
print(ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [21]:
a2=np.ones_like(a) # like the shape of a
print(a2)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


In [22]:
a3=np.full((2,2),5)
# a4=np.full_like(a3,2)
print(a3)

[[5 5]
 [5 5]]


In [23]:
np.random.random((4))

array([0.53760254, 0.72147864, 0.13342098, 0.44575479])

In [24]:
# Random decimal numbers
# glgl
'''
fffff
'''
# np.random.rand(3,2)
np.random.random(5)

array([0.54361466, 0.27440148, 0.25160709, 0.00141654, 0.47215995])

In [48]:
# Random int numbers
np.random.randint(0,3,size=(2),dtype='i')

array([1, 1])

In [26]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
a=np.ones((5,5))
print(a)
print('------------------')
b=np.zeros((3,3))
b[1,1]=9
print(b)
print('------------------')
print('* The final matrix *')
a[1:-1,1:-1]=b # from the second row to the before the last
print(a)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
------------------
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
------------------
* The final matrix *
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [28]:
a=np.array([1,0,0])
b=a
print(b)

[1 0 0]


calculations

In [29]:
a=np.array([1,2,3])
b=np.array([1,1,1])
print(a+b)
print('------------')
print(a*2)
print('------------')
print(a/2)
print('------------')
print(a+2)
print('------------')
print(a-2)
print('------------')
print(a**2) #(a^2)

[2 3 4]
------------
[2 4 6]
------------
[0.5 1.  1.5]
------------
[3 4 5]
------------
[-1  0  1]
------------
[1 4 9]


In [30]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [31]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [32]:
# np.round()
# np.floor()
# np.ceil()
#np.trunc()
# for more and more --> https://docs.scipy.org/doc/numpy/reference/routines.math.html
print(np.sum(a)) # calc the sum of elements

6


Linear Algebra --> for more functions https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

In [33]:
a=np.full((3,3),2)
np.linalg.det(a)  # المحدد  

0.0

Statistics

In [34]:
a=np.array([1,1,5])
print(max(a))
# min(a)
# sum(a)
# std(a)

5


Reshaping the arrays

In [51]:
before =np.full((2,3),5)  # take of the size 
before.resize((2,2)) # u can resize the matrix to reshape it
after=before.reshape((2,2))
print(after)

[[5 5]
 [5 5]]


In [36]:
stk1=np.zeros((2,2))
stk2=np.ones((2,2))
total=np.hstack((stk1,stk2)) # horizental 
print(total)

[[0. 0. 1. 1.]
 [0. 0. 1. 1.]]


In [37]:

total=np.vstack((stk1,stk2)) # vertical 
print(total)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]]


In [38]:
file=np.genfromtxt('data.txt',delimiter=',') # علي حسب انا فاصل بينهم ب اي ؟؟ 
file=file.astype('int32')
print(file)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]
