In [1]:
import numpy as np

a = np.array([1,2,3],dtype='int16') #'int 16 or 32 or 64 and so on'
# a = np.array([1,2,3],dtype='int')
# a = np.array([1,2,3],dtype='i16')
# a = np.array([1,2,3],dtype='i')

b=np.array([[1,2,3],[4,5,6]],dtype='int32') # 2d
print(b)

[[1 2 3]
 [4 5 6]]


In [2]:
a.shape

(3,)

In [7]:
a.ndim
a.nbytes
# a.dtype
# a.size #
# a.itemsize  # 2 bytes (16 bit)

6

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
print(a[0][2])

3


In [12]:
# print all the array 
print(a[:,:])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [28]:
# print first row
print(a[0,:])
# print first column
print(a[:,0])
# FIRST ELEMENT
print(a[0,0])
#    LAST ELEMENT
print(a[1,-1])
print(a[:])
print(a[:,0:4:1])

[1 2 3 4 5 6 7]
[1 8]
1
14
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  3  4]
 [ 8  9 10 11]]


In [33]:
# fill array with 5
a = np.full((2,2),5)
print(a)



[[5 5]
 [5 5]]


In [35]:
np.random.random((2,2))
np.random.randint(1,100,(2,2))

array([[95, 50],
       [22, 12]])

In [37]:
a=np.array([1,2,3])
b=np.array([1,1,1])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[2 3 4]
[0 1 2]
[1 2 3]
[1. 2. 3.]


In [38]:
#
a=np.array([1,23,4])
a.max()
a.min()
a.sum()
a.mean()
a.std()
a.var()

94.8888888888889

In [41]:
# read from file

a = np.genfromtxt('data.txt',delimiter=',',dtype='f')
print(a)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]
